name: Doxygen documentation

on:
  push:
    branches:
      - main
      - feature/github_actions
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2     
    - name: Create documentation
      uses: mattnotmitt/doxygen-action@v1.1.0
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
